/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    Info: typeof import('./src/components/Info.vue')['default']
    'Term copy': typeof import('./src/components/Term copy.vue')['default']
    Terminal: typeof import('./src/components/Terminal.vue')['default']
    'Terminal 0328': typeof import('./src/components/Terminal 0328.vue')['default']
    ToolBar: typeof import('./src/components/ToolBar.vue')['default']
  }
}
